export const FETCHING_RESOURCE = 'FETCHING_RESOURCE';
export const FETCHING_RESOURCE_SUCCESS = 'FETCHING_RESOURCE_SUCCESS';
export const FETCHING_RESOURCE_FAILURE = 'FETCHING_RESOURCE_FAILURE';

export const FETCHING_USER = 'FETCHING_USER';
export const FETCHING_USER_SUCCESS = 'FETCHING_USER_SUCCESS';
export const FETCHING_USER_FAILURE = 'FETCHING_USER_FAILURE';
